apps/coalio/urls.py
#encoding: utf-8
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

from tagger.views.api import TaggedPostResource

admin.autodiscover()

tagged_post = TaggedPostResource()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'profiles.views.home.login_view', name='home'),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^accounts/login/$', 'profiles.views.home.login_view', name='login'),
    url(r'^taggedposts/', include('tagger.urls', namespace='tagger')),
    url(r'^discussion/', include('discussions.urls', namespace='discussions')),
    url(r'^pages/', include('pages.urls', namespace='pages')),

    # API urls
    url(r'^api/', include(tagged_post.urls)),

    # 3rd party urls
    url(r'^search/', include('haystack.urls', namespace='search')),

    # admin urls
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/discussions/urls.py
# encoding: utf-8

from django.conf.urls import patterns, include, url

urlpatterns = patterns('discussions.views.home',
    url(r'^(?P<id>\d+)$', 'view_discussion', name='view'),
    url(r'^$', 'index', name='home'),
)

apps/pages/urls.py
# endoding: utf-8

from django.conf.urls import patterns, include, url

urlpatterns = patterns('pages.views.pages_view',
	url(r'^(?P<slug>[\w-]+)$', 'view_page', name='view'),
	url(r'^$', 'view_pages', name='home'),
)

apps/discussions/models.py
#encoding: utf-8

from django.db import models
from django.core.urlresolvers import reverse

from coalio.models.mixins import TimestampMixin

class Discussion(TimestampMixin):
    tagged_post = models.ForeignKey('tagger.TaggedPost')

    def __unicode__(self):
        return "Discussion about %s" % (self.tagged_post)

    def get_absolute_url(self):
        return reverse('discussions:view', args=[self.id])

class Reply(TimestampMixin):
    content = models.TextField()

    author = models.ForeignKey('profiles.CoalioUser')
    discussion = models.ForeignKey(Discussion)

    def __unicode__(self):
        return "%s's reply in %s" % (self.author, self.discussion)

    def get_absolute_url(self):
        return reverse('discussions:view', args=[self.id])

apps/discussions/forms.py
#encoding=utf-8

from django import forms

from models import Reply

class ReplyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ReplyForm, self).__init__(*args, **kwargs)
        self.fields['content'].widget.attrs['class'] = 'form-control'
    class Meta:
        model = Reply
        exclude = ('author', 'discussion')

apps/discussions/views/home.py
#encoding: utf-8

from django.shortcuts import render

from discussions.models import Discussion, Reply
from discussions.forms import ReplyForm

def view_discussion(request, id):
    template_name = 'discussions/discussion_view.html'
    ctx = {}
    discussion = Discussion.objects.get(id=id)
    ctx['discussion'] = Discussion.objects.get(id=id)

    reply_form = ReplyForm()
    ctx['reply_form'] = reply_form

    ctx['replies'] = Reply.objects.filter(discussion=discussion)

    if request.method == 'POST':
        reply_form = ReplyForm(request.POST)
        ctx['reply_form'] = reply_form
        if reply_form.is_valid:
            reply = reply_form.save(commit=False)
            reply.author = request.user
            reply.discussion = discussion
            reply.save()

    return render(request, template_name, ctx)


def index(request):
    template_name = 'discussions/discussion_list.html'
    ctx = {}
    ctx['discussions'] = Discussion.objects.all()
    return render(request, template_name, ctx)

apps/discussions/templates/discussions/_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <title>Coal.io {% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap  3.0 -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}" />
    <!-- custom sass-css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />

    {% block extra_css %}
    {% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->    

  </head>
  <body>
    <div id='wrap'>
    {% block navbar %}
        {# {% include 'coalio/navbar_includes/usernavbar.html' %} #}
    {% endblock %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message }}
        </div>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'discussions:home' %}"><img src="{% static 'img/icon-38.png' %}"/> YMCA Anti-Cyberbullying Project</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'discussions:home' %}">Home</a></li>
            <li><a href="{% url 'pages:view' slug='about' %}">About</a></li>
            <li><a href="{% url 'pages:view' slug='prevent-cyberbullying' %}">Prevent Cyberbullying</a></li>
            <li><a href="{% url 'pages:view' slug='report-cyberbullying' %}">Report Cyberbullying</a></li>
          </ul>
          <ul class="nav pull-right">
            <li style="float:left;"><a href="/accounts/login"><span class='glyphicon glyphicon-log-in'></span> Login</a></li>
            {# <li style="float:left;"><a href="/accounts/register">Sign Up</a></li> #}
        </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
    	<div class="main-view">
        {% block body %}
    	{% endblock %}
      </div>
    </div><!-- /container -->

    </div><!-- /wrap -->
    

    <footer class="navbar-collapse collapse" style="  background-color: #000000;color: #999999;padding-top:9px;position: fixed;bottom: 0;width: 100%;">
        <div class='container'>
        {% block footer %}
            {# {% include 'coalio/includes/footer.html' %} #}
        {% endblock %}
        <p><img src="{% static 'img/icon-16.png' %}" height="16" width="16"/> Created @ 2014 Hackdance PC,UT ☺ Coalio → [Faris, Michael, Sam, Joseph, Eric]</p>
        </div>
    </footer>

    {% block extra_js %}
    {% endblock %}
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

    
  </body>
</html>

apps/discussions/templates/discussions/chat.html
{% extends 'discussions/_base.html' %}

{% block content %}
{% endblock %}

apps/discussions/templates/discussions/discussion_list.html
{% extends "discussions/_base.html" %}

{% block title %}Discussions{% endblock %}

{% block body %}
<h1>Discussions</h1>
{% for discussion in discussions %}
  <h3 class='discussion-title'><a href='{{ discussion.get_absolute_url }}'>{{ discussion.tagged_post.content|truncatewords:5 }}</a></h3>

  <div style="text-align:left;">
    {{ discussions.tagged_post.content }}
  </div>
{% endfor %}
{% endblock %}

apps/discussions/templates/discussions/discussion_view.html
{% extends "discussions/_base.html" %}

{% block title %}Discussions{% endblock %}

{% block body %}
<h1>Discussion</h1>
<h3 class='discussion-title'>{{ discussion.tagged_post.content|safe }}</h3>
<p class='label label-info'><a href='{{ discussion.tagged_post.ref_url }}'>See post →</a></p>
<p class='text text-info'>{{ discussion.tagged_post.bully_social_id }}</p>

<div style="text-align:left;">
  {% for reply in replies %}
    <span>{{ reply.author }}: {{ reply.content }}</span><br/>
  {% endfor %}
</div>

<div class='reply-form'>
  <form role='form' action='#' method='POST'>
    {% csrf_token %}
    {% for field in reply_form %}
    <div class="form-group">
      {{ field.errors }}
      {{ field.label_tag }} {{ field }}
    </div>
    {% endfor %}
    <button class='btn btn-success'>Reply</button>
  </form>
</div>
{% endblock %}